#1
CREATE DATABASE ASSIGNMENT;

USE ASSIGNMENT;

#2
CREATE TABLE COUNTRIES (
NAME VARCHAR(20) NOT NULL,
POPULATION VARCHAR(50),
CAPITAL VARCHAR (20)
);

#3
INSERT INTO COUNTRIES (
NAME,POPULATION,CAPITAL)
VALUES ('China',1382,'Beijing'),
('India',1326,'Delhi'),
('United States',324,'Washington D.C.'),
('Indonesia',260,'Jakarta'),
('Brazil',209,'Brasilia'),
('Pakistan',193,'Islamabad'),
('Nigeria',187,'Abuja'),
('Bangladesh',163,'Dhaka'),
('Russia',143,'Moscow'),
('Mexico',128,'Mexico City'),
('Japan',126,'Tokyo'),
('Philippines',102,'Manila'),
('Ethiopia',101,'Addis Ababa'),
('Vietnam',94,'Hanoi'),
('Egypt',93,'Cairo'),
('Germany',81,'Berlin'),
('Iran',80,'Tehran'),
('Turkey',79,'Ankara'),
('Congo',79,'Kinshasa'),
('France',64,'Paris'),
('United Kingdom',65,'London'),
('Italy',60,'Rome'),
('South Africa',55,'Pretoria'),
('Myanmar',54,'Naypyidaw');


#3A
INSERT INTO COUNTRIES( NAME, POPULATION, CAPITAL)
VALUES ('UGANDA', 40, 'KAMPALA'),
('GREENLAND',10,'DENMARK')
; 

#3B
UPDATE COUNTRIES
SET CAPITAL = 'NEW DELHI'
WHERE CAPITAL = 'DELHI';


RENAME TABLE COUNTRIES TO BIG_COUNTRIES ;

#5
CREATE TABLE PRODUCT (
PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(50) NOT NULL UNIQUE ,
DESCRIPTION VARCHAR (100),
SUPPLIER_ID INT,
FOREIGN KEY (SUPPLIER_ID) references SUPPLIERS(SUPPLIER_ID) );

CREATE TABLE SUPPLIERS (
SUPPLIER_ID INT PRIMARY KEY AUTO_INCREMENT ,
SUPPLIER_NAME VARCHAR(50),
LOCATION VARCHAR(100) );

CREATE TABLE STOCKS (
ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT,
BALANCE_STOCK INT,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) );


SELECT * FROM SUPPLIERS;

#6
INSERT INTO SUPPLIERS (
SUPPLIER_NAME, LOCATION)
VALUES ( 'SRUSHTI', 'MYSORE'),
('SUSHMA','BENGALURU'),
('VIKAS','DURGA'),
('ATHANI','KODAGU');
;
SELECT *
FROM PRODUCT;

INSERT INTO PRODUCT (PRODUCT_NAME,DESCRIPTION,SUPPLIER_ID)
VALUES ('PHONE','IPHONE12',1),
('SPEAKER','JBL',2),
('TABLE','WOODEN',3),
('PROJECTOR','HITACHI',4);

SELECT *
FROM STOCKS;

SELECT *
FROM SUPPLIERS;

INSERT INTO STOCKS (PRODUCT_ID,BALANCE_STOCK)
VALUES (1, 23),
(2,22),
(3,87),
(4,55);

#7
ALTER TABLE SUPPLIERS
MODIFY SUPPLIER_NAME VARCHAR(50) NOT NULL UNIQUE;

#8
update emp set deptno = 10;
update emp set deptno = 20 where emp_id%2 = 0;
update emp set deptno = 30 where emp_id%3= 0;    
update emp set deptno = 40 where emp_id%4 = 0; 
update emp set deptno = 50 where emp_id%5 = 0;

#9
CREATE UNIQUE INDEX INDEX_NAME
ON EMP (EMP_NO);

SELECT *
FROM EMP;

#10
CREATE VIEW EMP_SAL AS
SELECT EMP_NO,FIRST_NAME,LAST_NAME,SALARY
FROM EMP
ORDER BY SALARY DESC;

SELECT *
FROM EMP_SAL;






