CREATE DATABASE HR;

USE HR;

CREATE TABLE EMPLOYEE (
EMPLOYEEID INT PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE VARCHAR(500),
GENDER INT,
HIREDATE DATETIME,
EMAIL	VARCHAR(500),
PHONE	CHAR(10),
CITYID INT,
DEPARTMENTID INT);

CREATE TABLE DEPARTMENT (
DEPARTMENTID INT PRIMARY KEY AUTO_INCREMENT ,
DEPARTMENT VARCHAR(500)
);

CREATE TABLE GENDER (
GENDERID INT PRIMARY KEY AUTO_INCREMENT,
GENDER VARCHAR(500)
);

CREATE TABLE CITY (
CITYID INT PRIMARY KEY AUTO_INCREMENT,
CITY VARCHAR(500)
);

ALTER TABLE EMPLOYEE
DROP GENDER;

ALTER TABLE EMPLOYEE
ADD GENDERID INT;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE_GENDERID
FOREIGN KEY(GENDERID) REFERENCES GENDER(GENDERID);
 
 ALTER TABLE EMPLOYEE 
 ADD CONSTRAINT FK_EMPLOYEE_CITYID
 FOREIGN KEY(CITYID) REFERENCES CITY(CITYID);
 
 ALTER TABLE EMPLOYEE 
 ADD CONSTRAINT FK_DEPARTMENT_DEPT_ID
 FOREIGN KEY(DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID);
 
 ALTER TABLE EMPLOYEE 
 ADD CONSTRAINT UK_EMPLOYEE_EMAIL
 UNIQUE (EMAIL);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT UK_EMPLOYEE_PHONE
UNIQUE(PHONE);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT CK_EMPLOYEE_PHONE
CHECK (LENGTH(PHONE)=10 AND PHONE NOT REGEXP '[A-Z]') ;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT CK_EMPLOYEE_EMAIL
CHECK (EMAIL LIKE '%@%');

DROP DATABASE APP;
#CREATE DATBASE BY NAME APP
CREATE DATABASE APP;

#CREATE TABLE USERS (USERID,USERNAME,LOGINID(TEXT),PASSWORD,EMAIL,COUNTRYID,PLANID,RATING)
CREATE TABLE USERS(
USERID INT  PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50),
LOGINID CHAR(6),
PASSWORD VARCHAR(6),
EMAIL VARCHAR(500),
COUNTRYID INT ,
PLANID INT,
RATING INT );
ALTER TABLE USERS
DROP PASSWORD;
ALTER TABLE USERS
ADD PASSWORD VARCHAR(500);

#CREATE TABLE PLAN(PLANID,PLAN)
CREATE TABLE PLAN (
PLANID INT PRIMARY KEY AUTO_INCREMENT,
PLAN VARCHAR(500));

#CREATE TABLE COUNTRY(COUNTRYID, COUNTRY, REGION ID)
CREATE TABLE COUNTRY (
COUNTRYID INT PRIMARY KEY AUTO_INCREMENT,
COUNTRY VARCHAR(50),
REGIONID INT );

#CREATE TABLE REGION(REGIONID,REGION)
CREATE TABLE REGION (
REGIONID INT PRIMARY KEY AUTO_INCREMENT,
REGION VARCHAR(50));

#FK COUNTRYID,PLANID..REGIONID IN COUNTRY
ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_COUNTRYID
FOREIGN KEY(COUNTRYID) REFERENCES COUNTRY(COUNTRYID);

ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_PLANID
FOREIGN KEY(PLANID) REFERENCES PLAN(PLANID);

ALTER TABLE COUNTRY
ADD CONSTRAINT FK_USERS_REGIONID
FOREIGN KEY(REGIONID) REFERENCES REGION(REGIONID);

#UNIQUE LOGINID, PASSWORD, EMAIL
ALTER TABLE USERS
ADD CONSTRAINT UK_USERS_LOGINID
UNIQUE(LOGINID);

ALTER TABLE USERS
ADD CONSTRAINT UK_USERS_PASSWORD
UNIQUE(PASSWORD);

ALTER TABLE USERS
ADD CONSTRAINT UK_USERS_EMAIL
UNIQUE(EMAIL);

#PLAN IN PLAN TABLE SHOULD HAVE VALUES A-D 
ALTER TABLE PLAN
DROP CONSTRAINT CK_PLAN;
ALTER TABLE PLAN
ADD CONSTRAINT CK_PLAN
CHECK (PLAN REGEXP '[A-D]' AND LENGTH(PLAN)=1);

# Password should be having min length 6 chars and contain atleast one number,one text and one special character
ALTER TABLE USERS
ADD CONSTRAINT CK_PASSWORDS
CHECK(LENGTH(PASSWORD)>=6 AND PASSWORD REGEXP '[A-Z]' AND PASSWORD REGEXP '[0-9]' AND PASSWORD REGEXP '!|@|#|$|%' );



# LoginId should be six characters exactly, first 3 characters should be numbers,last 3 CHARACTERS SHOULD BE TEXT

ALTER TABLE USERS
DROP CONSTRAINT CK_LOGINID;

# SIR METHOD

ALTER TABLE USERS
ADD CONSTRAINT CK_LLOGINID
CHECK (LENGTH(LOGINID) = 6 AND LOGINID REGEXP '[0-9][0-9][0-9][A-Z][A-Z][A-Z]');

INSERT INTO REGION(REGION)
VALUES ('ASIA'),
		('EUROPE'),
        ('AMERICA'),
        ('OCEANIA');
        
INSERT INTO PLAN(PLAN)
VALUES ('A'),('B'),('C'),('D');

INSERT INTO COUNTRY(COUNTRY,REGIONID)
VALUES ('INDIA',1),
 ('CHINA',1),
  ('JAPAN',1),
   ('FRANCE',2),
    ('ITALY',2),
 ('GERMANY',2),
  ('CANADA',3);
  
  INSERT INTO USERS
  VALUES (DEFAULT,'HITESH','123ABC','HIT23!','HITESHANALYST@GMAIL.COM',1,1,1),
  (DEFAULT,'JEET','122ABD','HIT13!','HITEHANALYST@GMAIL.COM',1,1,2),
  (DEFAULT,'NARESH','123HBC','HIH23!','HITESHANLYST@GMAIL.COM',1,2,1);

INSERT INTO USERS
VALUES(DEFAULT,'RAM','123ERD','RAMS@2','RAMANALYST2@GMAIL.COM', 1,1,1);

INSERT INTO USERS
VALUES(DEFAULT,'ABHISHEK','123QRD','ABHI@2','ABHILYST2@GMAIL.COM', 1,1,1);

DELETE FROM USERS
WHERE USERNAME= 'ABHISHEK';

SELECT *
FROM USERS;

DROP DATABASE HR;

set sql_safe

