CREATE TABLE STARFILMS AS
SELECT *
FROM MOVIES.FILM
WHERE TITLE REGEXP 'STAR';

SELECT *
FROM STARFILMS;

INSERT INTO STARFILMS
SELECT *
FROM MOVIES.FILM
WHERE TITLE REGEXP 'DARK';

DROP TABLE STARFILMS;